monkey_recog_phrases = [ #Keywords to activate monkey
    ":monkey:",
    ":gorilla:",
    ":orangutan:",
    ":monkey_face:",
    "monke",
    "monkey",
    "pimp",
    "pimps",
    "chimp",
    "chimpin",
    "chimps",
    "train",
    "orangutan",
    "orangutans"
    "gorilla",
    "gorillas",
    "banana",
    "bananas",
    "peanut",
    "peanuts",
    "primate",
    "primates",
    "ape",
    "apes",
    "mongoloid",
    "mongoloids"
]

monkey_emotes = [ #Emote responses to when someone triggers monkey keyword
    ":monkey:",
    ":gorilla:",
    ":orangutan:",
    ":monkey_face:",
    "<:squadW:645483642381926421>"
]
joker_recog_phrases = [ #Keywords to activate Joker
    "society",
    "societies",
    "racist",
    "racists",
    "racism",
    "funny",
    "prejudice",
    "terrorist",
    "terrorists",
    "terrorism",
    "abuse",
    "abuser",
    "abusers",
    "kino",
    "kinophile",
    "kinophiles",
    "a24",
    "misogyny",
    "phile",
    "philes",
    "pedo",
    "pedos",
    "pedophile",
    "pedophiles"
]

horny_recog_phrases = [ #Keywords to activate Horny
    "horny",
    "gasm",
    "hot",
    "sexy",
    "cute",
    "butt",
    "feet",
    "toes",
    "tits",
    "boobs",
    "<:triumph:805133291703369739>",
    "cum"
]
